[project]
name = 'Roboverse'
version = '0.0.0.dev0'

description = 'Robotics Metaverse'
readme = {file = 'README.md', content-type = 'text/markdown', charset = 'UTF-8'}

requires-python = '>= 3.10, < 4'

license = {file = 'LICENSE'}

authors = [
  {name = 'The Vinh LUONG (LƯƠNG Thế Vinh)', email = 'TheVinhLuong@gmail.com'}
]
maintainers = [
  {name = 'The Vinh LUONG (LƯƠNG Thế Vinh)', email = 'TheVinhLuong@gmail.com'}
]

keywords = [
  'Robotics',
  'robot',
  'robots',

  'Artificial Intelligence',
  'A.I.',
  'AI',

  'metaverse',
]

classifiers = [
  'Development Status :: 3 - Alpha',
  # 'Development Status :: 4 - Beta',
  # 'Development Status :: 5 - Production/Stable',
  # 'Development Status :: 6 - Mature',
  'Environment :: MacOS X',
  'Environment :: Win32 (MS Windows)',
  'Intended Audience :: Developers',
  'Intended Audience :: Education',
  'Intended Audience :: Information Technology',
  'Intended Audience :: Manufacturing',
  'Intended Audience :: Science/Research',
  'Operating System :: MacOS',
  'Operating System :: MacOS :: MacOS X',
  'Operating System :: Microsoft',
  'Operating System :: Microsoft :: Windows',
  'Operating System :: Microsoft :: Windows :: Windows 7',
  'Operating System :: Microsoft :: Windows :: Windows 8',
  'Operating System :: Microsoft :: Windows :: Windows 8.1',
  'Operating System :: Microsoft :: Windows :: Windows 10',
  'Operating System :: OS Independent',
  'Operating System :: Other OS',
  'Operating System :: POSIX',
  'Operating System :: POSIX :: Linux',
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: 3.11',
  'Topic :: Education',
  'Topic :: Home Automation',
  'Topic :: Scientific/Engineering',
  'Topic :: Scientific/Engineering :: Artificial Intelligence',
  'Topic :: Scientific/Engineering :: Human Machine Interfaces',
  'Topic :: Scientific/Engineering :: Mathematics',
  'Topic :: Scientific/Engineering :: Physics',
  'Topic :: Scientific/Engineering :: Visualization',
  'Topic :: Software Development',
  'Topic :: Software Development :: Libraries',
  'Topic :: Software Development :: Libraries :: Application Frameworks',
  'Topic :: Software Development :: Libraries :: Python Modules',
  'Topic :: Software Development :: User Interfaces',
  'Topic :: Software Development :: Widget Sets',
]


[project.urls]
Homepage = 'https://GitHub.com/Mindstem/Roboverse'
Repository = 'https://GitHub.com/Mindstem/Roboverse'
GitHub = 'https://GitHub.com/Mindstem/Roboverse'
Documentation = 'https://Mindstem.GitHub.io/Roboverse'


[project.dependencies]


[project.optional-dependencies]
doc = [
  # Sphinx & related
  'Sphinx >= 4.3.2',
  'Sphinx-AutoBuild >= 2021.3.14',
  'SphinxContrib-JSMath >= 1.0.1',

  # Markdown
  'CommonMark >= 0.9.1',
  'MyST-Parser >= 0.16.1',
  'ReCommonMark >= 0.7.1',
]

lint = [
  'Bandit >= 1.7.1',
  'Flake8 >= 4.0.1',
  'MyPy >= 0.930',
  'Prospector >= 1.5.3.1',
  'PyCodeStyle >= 2.8.0',
  'PyDocStyle >= 6.1.1',
  'PyLama >= 8.3.6',
  'PyLint >= 2.12.2',

  'Black >= 21.12',
]

test = [
  'Nose >= 1.3.7',
  'Nose2 >= 0.10.0',
  'PyTest >= 6.2.5',
  'UnitTest2 >= 1.1.0',
]


[project.scripts]

# [project.gui-scripts]

# [project.entry-points."spam.magical"]


[build-system]
requires = [
  'SetUpTools >= 60.1.0',
  'Wheel >= 0.37.1',
]
build-backend = 'setuptools.build_meta'
